
# Website information
title: Ujjwal Bansal
description: A personal website for information about me and some of my projects. 
name: Ujjwal Bansal
masthead_title: "Ujjwal's Website"

# Template setup
minimal_mistakes_skin: "aqua"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Template configuration
date_format: "%_d %b %Y"

# defaults
defaults:
  - values:
      show_date: true

# author
author:
  name: 'Ujjwal Bansal'
  avatar: '/assets/images/avatar.jpg'
  bio: 'Data Scientist'
  location: 'Sydney'
  links:
    - label: 'Github'
      icon: 'fab fa-github'
      url: 'https://github.com/ujjwal-bansal'
    - label: 'LinkedIn'
      icon: 'fab fa-linkedin'
      url: 'https://www.linkedin.com/in/ujjwal-bansal-anu/'
    - label: 'Tableau'
      icon: 'fas fa-table'
      url: 'https://public.tableau.com/app/profile/ujjwal.bansal6244/vizzes'

# Plugins
plugins:
  - jekyll-include-cache
