
# Website information
title: Ujjwal Bansal
description: A personal website for information about me and some of my projects. 
name: Ujjwal Bansal
masthead_title: "Ujjwal's Website"

# Template setup
minimal_mistakes_skin: "aqua"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Template configuration
date_format: "%_d %b %Y"

# defaults
defaults:
  - values:
      show_date: true


# Plugins
plugins:
  - jekyll-include-cache

# author
author:
  name: 'Ujjwal Bansal'
  avatar: '/assets/images/avatar.jpg'
  bio: 'Data Scientist
  location: 'Sydney'
  links:
    - label: 'Github'
      icon: '/assets/icons/github.png/'
      url: 'https://github.com/ujjwal-bansal'
    - label: 'LinkedIn'
      icon: 'assets/icons/LinkedIn.png/'
      url: 'https://www.linkedin.com/in/ujjwal-bansal-anu/
    - label: 'Tableau'
      icon: 'assets/icons/tableau.png'
      url: 'https://public.tableau.com/app/profile/ujjwal.bansal6244/vizzes'
